### ISSUE TITLE
端口全开，显示unknow

### ISSUE THREAD

**Issue by go-spider** [XinRoom/go-portScan#11]
./go-portScan_linux -ip x.x.x.x --Pn --sT --sV --httpx
端口全开，显示unknow，nmap或者其他扫描工具扫描无问题，请联系spider146@outlook.com？方便给测试IP
@XinRoom

**Comment by XinRoom** [comment]
感谢反馈，已经在 [fix: 在tcp + sV/httpx模式下由于只判断了timeout状态，未对其它错误（比如RST）判断，导致在对端发送RST包的情况下误认为端口开放](https://github.com/XinRoom/go-portScan/commit/51b18bb0958117529e7965af752575b7c9dd2b40) 进行了修复。

可以pull后编译测试。

**Comment by go-spider** [comment]
@XinRoom 复测已经修复
