### ISSUE TITLE
tcp扫描模式 -rate 是不是存在bug

### ISSUE THREAD

**Issue by Miracles666** [XinRoom/go-portScan#13]
如图所示：
![image](https://github.com/XinRoom/go-portScan/assets/40236845/049c6a5d-fcb1-4714-ab1d-d6603d1f971b)

貌似速度没有多大的变化。

**Comment by XinRoom** [comment]
确实有点问题，限速器桶大小设置的太小了

**Comment by XinRoom** [comment]
优化于 https://github.com/XinRoom/go-portScan/commit/b3e3087eae177826adc677b2299ed9a4ff96a858

**Comment by Miracles666** [comment]
貌似还是有点问题 我已经按照https://github.com/XinRoom/go-portScan/commit/b3e3087eae177826adc677b2299ed9a4ff96a858 修改了代码 但是效果还是差不多

**Comment by Miracles666** [comment]
![image](https://github.com/XinRoom/go-portScan/assets/40236845/2d8b2425-85a2-4cc8-9d6f-13e10333d6c3)

**Comment by Miracles666** [comment]
![image](https://github.com/XinRoom/go-portScan/assets/40236845/2d8b2425-85a2-4cc8-9d6f-13e10333d6c3)

**Comment by XinRoom** [comment]
我看我这个区别还挺明显的啊
![image](https://github.com/XinRoom/go-portScan/assets/32238570/e770caf4-b552-4144-ad82-65a43dce0090)

**Comment by Miracles666** [comment]
可以发一下 你的版本给我吗 我这边测试一下

**Comment by XinRoom** [comment]
[go-portScan.zip](https://github.com/XinRoom/go-portScan/files/11526823/go-portScan.zip)

**Comment by Miracles666** [comment]
难道是我网络的问题？ 有没有可能是我扫的对象是虚拟机的原因。
![image](https://github.com/XinRoom/go-portScan/assets/40236845/ea648263-d049-49bc-b50d-c835ed7e6f2f)

**Comment by XinRoom** [comment]
为什么你10000比3000还慢。这个也会受限于硬件环境，换个环境试一试呢

**Comment by Miracles666** [comment]
很吃CPU，这次我扫的是本机ip 。
![image](https://github.com/XinRoom/go-portScan/assets/40236845/eb31340c-cc49-4fbd-adad-e3c5a37c7033)
![image](https://github.com/XinRoom/go-portScan/assets/40236845/c61dd96d-b3ea-41cc-9d4c-5ccd15aa0668)

**Comment by Miracles666** [comment]
你能发我一个 linux版本的吗 我放到服务器测试一下

**Comment by XinRoom** [comment]
[go-portScan_linux.zip](https://github.com/XinRoom/go-portScan/files/11526915/go-portScan_linux.zip)

**Comment by Miracles666** [comment]
谢谢 @XinRoom  确实是我本机环境的问题
