### ISSUE TITLE
[error] Initialize Scanner: get router info fail: no dev name

### ISSUE THREAD

**Issue by aaq1adqwe** [XinRoom/go-portScan#15]
[error] Initialize Scanner: get router info fail: no dev name

权限为：nt authority\network service

好像是因为权限问题无法进行扫描

**Comment by XinRoom** [comment]
手动指定下网卡看，可以通过--nexthop参数指定对应网卡的网关IP地址

**Comment by XinRoom** [comment]
之前有一处 error 忘了收集，改进了下，这样就能明确知道错误信息了 https://github.com/XinRoom/go-portScan/commit/1913faba76ae0c50c33e86af20ab82be97a0ef88
