### ISSUE TITLE
有个bug

### ISSUE THREAD

**Issue by woshinibabao1** [XinRoom/go-portScan#16]
![image](https://github.com/XinRoom/go-portScan/assets/136443419/2d663c8c-ce2c-4550-8cdd-84448bcf6399)
扫不出指纹，都没显示端口是开是关了

**Comment by XinRoom** [comment]
不对啊，你这是syn模式下扫描服务，该模式下是先syn判断端口是否打开，然后再tcp判断服务，就算服务判断不出来，也会显示为unknow啊
