### ISSUE TITLE
关于与nmap进行性能对比的问题

### ISSUE THREAD

**Issue by mythldy** [XinRoom/go-portScan#17]
nmap性能对比时发现存在巨大差距，请问有优化方式吗，我使用readme里面的示例进行操作的，麻烦大佬给解答下

**Comment by XinRoom** [comment]
readme里面的示例，主要是为了体现端口扫描逻辑，没有对主机发现的ping逻辑优化，是单线程的，所以比较慢
可以使用如下方式进行并发优化：
https://github.com/XinRoom/go-portScan/blob/9a0b5f8d2bd26ed6ed4f502c2f34d9e806c8b2c1/cmd/go-portScan.go#L284-L293

**Comment by XinRoom** [comment]
已提交新的示例
