### ISSUE TITLE
wgIpsLive并发问题

### ISSUE THREAD

**Issue by kN6jq** [XinRoom/go-portScan#18]
https://github.com/XinRoom/go-portScan/blob/main/cmd/go-portScan.go#L127
你好，我在学习你的代码，发现一个问题，如上

![image](https://github.com/XinRoom/go-portScan/assets/27048404/9bbea585-4f1e-475d-aa5b-20177e0b1de1)

这个wgIpsLive 是否会因为netLive导致死锁？

![image](https://github.com/XinRoom/go-portScan/assets/27048404/65f685c5-4315-48a4-87f2-c10ba7da736a)

**Comment by XinRoom** [comment]
没毛病啊，done之前必然有add

**Comment by XinRoom** [comment]
你可以理解为，前面是函数定义，后面才调用
