### ISSUE TITLE
Initialize Scanner: no syn support 和其他几个小问题

### ISSUE THREAD

**Issue by winezer0** [XinRoom/go-portScan#19]
go-portScan-nosyn.exe --ip 1.1.1.1  -p 1-65535  --sV --httpx  --oC out.csv  --Pn --rate 200
[error] Initialize Scanner: no syn support
 go-portScan-nosyn.exe --ip 1.1.1.1  -p 1-65535  --sV --httpx  --oC out.csv  --Pn --rate 200 -sS
[error] Initialize Scanner: no syn support

使用的nosyn编译模式，生成的exe好像没法执行

**Comment by winezer0** [comment]
linux版本不能在windows上编译吗？可以发布一下release吗

**Comment by winezer0** [comment]
1.1.1.1:53 unknown
1.1.1.1:853 unknown

识别53端口好像不支持

**Comment by XinRoom** [comment]
> go-portScan-nosyn.exe --ip 1.1.1.1 -p 1-65535 --sV --httpx --oC out.csv --Pn --rate 200 [error] Initialize Scanner: no syn support go-portScan-nosyn.exe --ip 1.1.1.1 -p 1-65535 --sV --httpx --oC out.csv --Pn --rate 200 -sS [error] Initialize Scanner: no syn support
> 
> 使用的nosyn编译模式，生成的exe好像没法执行

是提示`[error] Initialize Scanner: no syn support`，因为禁用了syn模式，需要手动指定使用tcp模式，加入参数`-sT`

**Comment by XinRoom** [comment]
> 1.1.1.1:53 unknown 1.1.1.1:853 unknown
> 
> 识别53端口好像不支持

目前端口主要识别的是数据库、远程控制类的端口，没有识别dns，指纹见：https://github.com/XinRoom/go-portScan/blob/main/core/port/fingerprint/rules.go

**Comment by XinRoom** [comment]
> linux版本不能在windows上编译吗？可以发布一下release吗

由于依赖pcap库，带syn的linux版本只能在linux下编译（使用nosyn模式可跨平台编译）
在有docker的linux主机上执行 sh ./build/build_static_alpine.sh 即可生成linux的二进制程序

**Comment by winezer0** [comment]
好的
