### ISSUE TITLE
syn扫描器中队列缓冲区调整判断似乎存在bug

### ISSUE THREAD

**Issue by yuanchenyyy** [XinRoom/go-portScan#21]
具体位置在syn.go的149行到158行

	// 与recv协同，当队列缓冲区到达80%时降半速，90%将为1/s
	if len(ss.openPortChan)*10 >= cap(ss.openPortChan)*8 {
		if ss.option.Rate/2 != 0 {
			ss.limiter.SetLimit(limiter.Every(time.Second / time.Duration(ss.option.Rate/2)))
		}
	} else if len(ss.openPortChan)*10 >= cap(ss.openPortChan)*9 {
		ss.limiter.SetLimit(1)
	} else {
		ss.limiter.SetLimit(limiter.Every(time.Second / time.Duration(ss.option.Rate)))
	}

问题存在于这里第二个else if

因为第一个if条件涵盖了第二个判断条件

**Comment by XinRoom** [comment]
确实有误，fix:https://github.com/XinRoom/go-portScan/commit/c19feb9f98b8b6a00b1d46d6184869bbd780bea9
