### ISSUE TITLE
只探测单个端口不出结果，这个端口混在很多端口里一起探测才能探测出来结果

### ISSUE THREAD

**Issue by Ti0oik** [XinRoom/go-portScan#24]
我直接用示例的代码，对单个端口，比如说22进行端口探测，探测不出来是否存活，但是用了top1000去探测就能探测出来22是存活的，大佬帮忙看看这是什么原因造成的，以下是我的代码：

```
import (
	"log"
	"net"
	"sync"
	"testing"
	"time"

	"github.com/XinRoom/go-portScan/core/port"
	"github.com/XinRoom/go-portScan/core/port/syn"
	"github.com/XinRoom/iprange"
	"github.com/panjf2000/ants/v2"
)

func TestMain(t *testing.T) {
	//single := make(chan struct{})
	retChan := make(chan port.OpenIpPort, 65535)
	// go func() {
	// 	//for ret := range retChan {
	// 	//	log.Println(ret)
	// 	//}
	// 	single <- struct{}{}
	// }()

	// 解析端口字符串并且优先发送 TopTcpPorts 中的端口, eg: 1-65535,top1000
	ports, err := port.ShuffleParseAndMergeTopPorts("22")
	if err != nil {
		log.Fatal(err)
	}

	log.Println(ports)

	// parse ip
	it, startIp, _ := iprange.NewIter("10.0.8.55")

	// scanner
	ss, err := syn.NewSynScanner(startIp, retChan, syn.DefaultSynOption)
	if err != nil {
		log.Fatal(err)
	}

	// port scan func
	portScan := func(ip net.IP) {
		for _, _port := range ports { // port
			ss.WaitLimiter()
			err := ss.Scan(ip, _port) // syn 不能并发，默认以网卡和驱动最高性能发包
			if err != nil {
				log.Println(err)
			}
		}
	}

	// Pool - ping and port scan
	var wgPing sync.WaitGroup
	poolPing, _ := ants.NewPoolWithFunc(50, func(ip interface{}) {
		_ip := ip.(net.IP)
		//if host.IsLive(_ip.String(), true, 800*time.Millisecond) {
		portScan(_ip)
		//}
		wgPing.Done()
	})
	defer poolPing.Release()

	start := time.Now()
	for i := uint64(0); i < it.TotalNum(); i++ { // ip索引
		ip := make(net.IP, len(it.GetIpByIndex(0)))
		copy(ip, it.GetIpByIndex(i)) // Note: dup copy []byte when concurrent (GetIpByIndex not to do dup copy)
		wgPing.Add(1)
		poolPing.Invoke(ip)
	}

	wgPing.Wait()
	ss.Close()
	//<-single
	log.Println(time.Since(start))
	log.Println(len(retChan))
```

**Comment by Andrez092** [comment]
download
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
If you don't have the c compliator, install it.(gcc or clang)

**Comment by XinRoom** [comment]
看起来是没有等待结果管道retChan输入和输出的结束，使用我示例原始的retChan结束判断信号试一试（single逻辑）

**Comment by Ti0oik** [comment]
> 看起来是没有等待结果管道retChan输入和输出的结束，使用我示例原始的retChan结束判断信号试一试（single逻辑），主程序需要等待retChan被扫描携程close信号
按照原始示例试了下，单个端口还是没法探测，我抓了个包，发现没有回最后的RST包，感觉是从哪里给断开了 
![image](https://github.com/user-attachments/assets/de350682-39d9-4515-b49c-43f9cd3326ef)

**Comment by Ti0oik** [comment]
> 看起来是没有等待结果管道retChan输入和输出的结束，使用我示例原始的retChan结束判断信号试一试（single逻辑），主程序需要等待retChan被扫描携程close信号

按照原始示例试了下，单个端口还是没法探测，我抓了个包，发现没有回最后的RST包，感觉是从哪里给断开了
![image](https://github.com/user-attachments/assets/a7dbb13b-da5f-4f44-bc97-0ed8edc286d4)

**Comment by Ti0oik** [comment]
> > 看起来是没有等待结果管道retChan输入和输出的结束，使用我示例原始的retChan结束判断信号试一试（single逻辑），主程序需要等待retChan被扫描携程close信号
> 
> 按照原始示例试了下，单个端口还是没法探测，我抓了个包，发现没有回最后的RST包，感觉是从哪里给断开了 ![image](https://private-user-images.githubusercontent.com/173782920/369266868-a7dbb13b-da5f-4f44-bc97-0ed8edc286d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY4MDkzMTMsIm5iZiI6MTcyNjgwOTAxMywicGF0aCI6Ii8xNzM3ODI5MjAvMzY5MjY2ODY4LWE3ZGJiMTNiLWRhNWYtNGY0NC1iYzk3LTBlZDhlZGMyODZkNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMFQwNTEwMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jN2M1NDgzNGU2Njk1NGFkNWY0OGI5ZTYwOGZiYzM5ZjM1MmJmMzMwYWRkOWE1ZDk1N2M5NDc2ODIxMDUzYjY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4SvoSQdC5kjVVTHax-8UZAPttSCiCff7iT7PLXDsspg)

![image](https://github.com/user-attachments/assets/3ca54943-821c-4707-935e-bcc4116616fd)

**Comment by XinRoom** [comment]
看了下，需要加个`ss.Wait()`，是忘了更新readme的示例代码，见：https://github.com/XinRoom/go-portScan/commit/7377c55e060065e5a2ec432eb41657299b18aa4b
