### ISSUE TITLE
希望能添加docker编译

### ISSUE THREAD

**Issue by lcc777** [XinRoom/go-portScan#8]
希望能添加DockerFile，我尝试在Windows下交叉编译，但是编译不通过，
通过docker编译出来的放到其他Linux运行提示：lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./go-portScan)
我找了些资料，大概是动态链接库的问题，不过这方面不太明白怎么解决

**Comment by XinRoom** [comment]
已安排 https://github.com/XinRoom/go-portScan/commit/f901b43065d7d4f59342732e1035d45435a2a4ac

**Comment by lcc777** [comment]
> 已安排 [f901b43](https://github.com/XinRoom/go-portScan/commit/f901b43065d7d4f59342732e1035d45435a2a4ac)

非常感谢~
