### ISSUE TITLE
能不能把output.log取消

### ISSUE THREAD

**Issue by Ajmd007** [XinRoom/go-portScan#9]
能不能把output.log取消

**Comment by XinRoom** [comment]
要不输出log文件吗

**Comment by Ajmd007** [comment]
就给我一个选择的权利，我不想要这么个东西

**Comment by XinRoom** [comment]
可以，我加个参数，不过我得想想默认是打开还是关闭

**Comment by XinRoom** [comment]
Modify in https://github.com/XinRoom/go-portScan/commit/6a62fc3d391292430482dd56f2834f7e4c453b41
